### ISSUE TITLE
JavaScript Client for Node.js Incorrect Example

### ISSUE THREAD

**Issue by JeffZ-1320** [SendSafely/JavaScript-Node-Client-API#3]
Link to the documentation: https://sendsafely.zendesk.com/hc/en-us/articles/360042056772

The example in the documentation is missing the keyCode parameter.

![sourceCode](https://user-images.githubusercontent.com/76709031/120507081-804c6b00-c394-11eb-8070-a84b6580cdbb.png)
![errorGuide](https://user-images.githubusercontent.com/76709031/120507083-80e50180-c394-11eb-99ce-6ab4883e7261.png)

**Comment by SendSafely-GitHub** [comment]
Fixed
